version: "3"
services:

  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - app

  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=bottle-water
      - MYSQL_ROOT_PASSWORD=Delta9+9chaos
    ports:
      - '3307:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  app:
    container_name: water-storage-app
    build:
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      -spring.datasource.username: root
      -spring.datasource.url: jdbc:mysql://mysql/bottle-water
      -spring.datasource.password: Delta9+9chaos
    ports:
    - "8080:8080"
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy


